---
language: python
python: "3.6"
addons:
  apt:
    packages:
      - python-pip
install:
  # Install ansible
  - pip install git+https://github.com/ansible/ansible#egg=ansible
script:
  # Basic role syntax check
  - ls -l roles/actual/
  - ansible-playbook --check -t common site.yml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
