language: python
python: "3.6"
addons:
  apt:
    packages:
      - python-pip
install:
  - pip install git+https://github.com/ansible/ansible#egg=ansible
script:
  - ansible-playbook --skip-tags linode --private-key roles/common/files/travis --check site.yml
notifications:
  webhooks: 
    - https://galaxy.ansible.com/api/v1/notifications/
before_install:
  - openssl aes-256-cbc -K $encrypted_3d8478623bf6_key -iv $encrypted_3d8478623bf6_iv
    -in roles/common/files/travis.enc -out roles/common/files/travis -d
