---
language: python
python: "3.6"
addons:
  apt:
    packages:
      - python-pip
install:
  # Install ansible
  - >
      git clone --single-branch -b mazer_role_loader
      https://github.com/edwardtheharris/ansible
  - pip install -e ansible/
  - pip install git+https://github.com/ansible/mazer.git
  - . ansible/hacking/env-setup
  - mazer install edwardtheharris.jenkins
script:
  # Basic role syntax check
  - ls -l roles/actual/
  - >
      ansible-playbook
      roles/actual/tests/test.yml -i
      roles/actual/tests/inventory --syntax-check
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
