---
- name: Create Jenkins home directory.
  git:
    repo: https://github.com/edwardtheharris/jenkins
    dest: /opt/roles/jenkins
    force: "yes"
- name: Copy the Jenkins NGINX config.
  template:
    src: nginx.jenkins.j2
    dest: /opt/roles/jenkins/roles/actual/files/nginx/conf.d/default.conf
- name: Create the Jenkins Docker network.
  docker_network:
    name: jenkins
- name: Create Docker volumes.
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - nginx_conf
    - jenkins_home
- name: Start Jenkins Alpine container.
  docker_container:
    name: "{{ jenkins_hostname }}"
    image: jenkins/jenkins:alpine
    hostname: "{{ jenkins_hostname }}"
    state: started
    restart_policy: always
    volumes:
      - jenkins_home
    published_ports:
      - 8080:8080
    networks:
      - name: jenkins
- name: Install Python on Jenkins container.
  command: >
           docker exec --user root {{ jenkins_hostname }}
           apk add --no-cache python
- name: Start NGINX Alpine container.
  docker_container:
    name: nginx
    image: nginx:alpine
    hostname: "nginx.{{ master_host }}"
    state: started
    restart_policy: always
    volumes:
      - /opt/roles/jenkins-actual/files/nginx:/etc/nginx:rw
    published_ports:
      - 80:80
      - 443:443
    networks:
      - name: jenkins
- name: Install Python on NGINX container.
  command: docker exec --user root nginx apk add --no-cache python
...
