---
- name: Configure Docker network.
  include_tasks: network.yml

- name: Configure Docker volumes.
  include_tasks: volumes.yml

- name: Start the Jenkins container.
  include_tasks: container.yml

- name: Run playbook on remote.
  include_tasks: playbook.yml

- name: Copy nginx conf volume.
  copy:
    src: files/nginx/
    dest: /var/lib/docker/volumes/nginx_conf/_data/
  become: "yes"

- name: Copy the Jenkins NGINX config.
  template:
    src: nginx.jenkins.j2
    dest: /var/lib/docker/volumes/nginx_conf/_data/conf.d/default.conf
  become: "yes"

- name: Start NGINX Alpine container.
  docker_container:
    name: nginx
    image: nginx:alpine
    hostname: nginx
    state: started
    restart_policy: always
    volumes:
      - nginx_conf:/etc/nginx
    published_ports:
      - 80:80
      - 443:443
    networks:
      - name: jenkins

- name: Install Python on NGINX container.
  command: docker exec --user root nginx apk add --no-cache python
...
