---
- name: Create a new Linode
  linode:
    name: jenkins-actual
    state: present
    region: us-west
    image: linode/arch
  register: linode_creation
- debug:
    var: linode_creation
# tasks file for actual
...
