---
- name: Template inventory.
  template:
    src: inventory.j2
    dest: /etc/ansible/hosts

- name: Copy playbook.
  copy:
    src: jenkins.yml
    dest: /tmp/jenkins.yml

- name: Execute playbook.
  command: ansible-playbook -i "{{ jenkins_hostname }}" /tmp/jenkins.yml
  register: result

- debug:
    var: result
...
