---
- name: Install Docker in Jenkins container.
  apk:
    name: "{{ item }}"
    state: present
    update_cache: "yes"
  loop:
    - bash
    - docker
    - python3
    - wget
- name: Get pip.
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
- name: Install pip.
  command: "{{ item}} /tmp/get-pip.py"
  loop:
    - /usr/bin/python
    - /usr/bin/python3
- name: Install missing Python libraries.
  pip:
    name: "{{ item }}"
    state: present
    executable: /usr/bin/pip3
  loop:
    - pytest
    - testinfra
    - linode_api4
- name: Update repositories.
  lineinfile:
    dest: /etc/apk/repositories
    line: http://nl.alpinelinux.org/alpine/edge/testing
    state: present
- name: Install man-db.
  apk:
    update_cache: "yes"
    name: man-db
    state: present
...
