---
- name: Install some utilities.
  pacman:
    update_cache: yes
    name: sudo,docker,git
    state: present
- name: Set the hostname.
  hostname:
    name: "{{ inventory_hostname }}"
- name: Copy updated sudoers.
  copy:
    src: sudoers
    dest: /etc/sudoers
- name: Copy updated sshd.
  copy:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ item }}"
  loop:
    - ssh_config
    - sshd_config
- name: Restart sshd service.
  service:
    name: sshd
    state: restarted
- name: Start Docker daemon.
  service:
    name: docker
    state: started
    enabled: "yes"
- name: Download pip install.
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
- name: Install pip.
  command: python /tmp/get-pip.py
- name: Install Docker Python module.
  pip:
    state: present
    name: docker
- name: Create roles directory.
  file:
    dest: /opt/roles/
    owner: duchess
    group: docker
    state: directory
...
